
  name: untitled1
  description: A simple, clean UI-only Flutter app named Changelog.
  version: 1.0.0+1
  publish_to: 'none'

  environment:
    sdk: '>=3.7.2 <4.0.0'

  dependencies:
    flutter:
      sdk: flutter
    cupertino_icons: ^1.0.8
    flutter_spinkit: ^5.1.0

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^5.0.0

  flutter:
    uses-material-design: true
    fonts:
      - family: Nunito
        fonts:
          - asset: assets/fonts/Nunito-Regular.ttf
          - asset: assets/fonts/Nunito-Bold.ttf
            weight: 700
    assets:
      - assets/fonts/
      - assets/images/